// Code generated by protoc-gen-go.
// source: auth.proto
// DO NOT EDIT!

/*
Package authpb is a generated protocol buffer package.

It is generated from these files:
	auth.proto

It has these top-level messages:
	ProfileRequest
	ProfileResponse
*/
package authpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// User's name.
type ProfileRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *ProfileRequest) Reset()                    { *m = ProfileRequest{} }
func (m *ProfileRequest) String() string            { return proto.CompactTextString(m) }
func (*ProfileRequest) ProtoMessage()               {}
func (*ProfileRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Complete user's profile.
type ProfileResponse struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	FullName string `protobuf:"bytes,2,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
}

func (m *ProfileResponse) Reset()                    { *m = ProfileResponse{} }
func (m *ProfileResponse) String() string            { return proto.CompactTextString(m) }
func (*ProfileResponse) ProtoMessage()               {}
func (*ProfileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*ProfileRequest)(nil), "authpb.ProfileRequest")
	proto.RegisterType((*ProfileResponse)(nil), "authpb.ProfileResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Auth service

type AuthClient interface {
	// Returns  user's profile.
	Profile(ctx context.Context, in *ProfileRequest, opts ...client.CallOption) (*ProfileResponse, error)
}

type authClient struct {
	c           client.Client
	serviceName string
}

func NewAuthClient(serviceName string, c client.Client) AuthClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "authpb"
	}
	return &authClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *authClient) Profile(ctx context.Context, in *ProfileRequest, opts ...client.CallOption) (*ProfileResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Auth.Profile", in)
	out := new(ProfileResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthHandler interface {
	// Returns  user's profile.
	Profile(context.Context, *ProfileRequest, *ProfileResponse) error
}

func RegisterAuthHandler(s server.Server, hdlr AuthHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Auth{hdlr}, opts...))
}

type Auth struct {
	AuthHandler
}

func (h *Auth) Profile(ctx context.Context, in *ProfileRequest, out *ProfileResponse) error {
	return h.AuthHandler.Profile(ctx, in, out)
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0xb1, 0x0b, 0x92, 0x94, 0x74, 0xb8, 0xf8,
	0x02, 0x8a, 0xf2, 0xd3, 0x32, 0x73, 0x52, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xa4,
	0xb8, 0x38, 0x4a, 0x8b, 0x53, 0x8b, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0xe0, 0x7c, 0x25, 0x27, 0x2e, 0x7e, 0xb8, 0xea, 0xe2, 0x82, 0xfc, 0xbc, 0xe2, 0x54, 0x21,
	0x21, 0x2e, 0x16, 0x24, 0xa5, 0x60, 0xb6, 0x90, 0x34, 0x17, 0x67, 0x5a, 0x69, 0x4e, 0x4e, 0x3c,
	0x58, 0x82, 0x09, 0x62, 0x06, 0x48, 0xc0, 0x2f, 0x31, 0x37, 0xd5, 0xc8, 0x85, 0x8b, 0xc5, 0xb1,
	0xb4, 0x24, 0x43, 0xc8, 0x86, 0x8b, 0x1d, 0x6a, 0x96, 0x90, 0x98, 0x1e, 0xc4, 0x35, 0x7a, 0xa8,
	0x4e, 0x91, 0x12, 0xc7, 0x10, 0x87, 0x58, 0xaa, 0xc4, 0x90, 0xc4, 0x06, 0xf6, 0x86, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x72, 0xee, 0x97, 0xcb, 0xd4, 0x00, 0x00, 0x00,
}
