// Code generated by protoc-gen-go.
// source: dbaccessor.proto
// DO NOT EDIT!

/*
Package dbaccessorpb is a generated protocol buffer package.

It is generated from these files:
	dbaccessor.proto

It has these top-level messages:
	UserRequest
	UserResponse
*/
package dbaccessorpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// User's name.
type UserRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
}

func (m *UserRequest) Reset()                    { *m = UserRequest{} }
func (m *UserRequest) String() string            { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()               {}
func (*UserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Complete user profile.
type UserResponse struct {
	Name     string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	FullName string `protobuf:"bytes,2,opt,name=full_name,json=fullName" json:"full_name,omitempty"`
}

func (m *UserResponse) Reset()                    { *m = UserResponse{} }
func (m *UserResponse) String() string            { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()               {}
func (*UserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*UserRequest)(nil), "dbaccessorpb.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "dbaccessorpb.UserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for DBAccessor service

type DBAccessorClient interface {
	// Returns detailed user profile.
	User(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserResponse, error)
}

type dBAccessorClient struct {
	c           client.Client
	serviceName string
}

func NewDBAccessorClient(serviceName string, c client.Client) DBAccessorClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "dbaccessorpb"
	}
	return &dBAccessorClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *dBAccessorClient) User(ctx context.Context, in *UserRequest, opts ...client.CallOption) (*UserResponse, error) {
	req := c.c.NewRequest(c.serviceName, "DBAccessor.User", in)
	out := new(UserResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DBAccessor service

type DBAccessorHandler interface {
	// Returns detailed user profile.
	User(context.Context, *UserRequest, *UserResponse) error
}

func RegisterDBAccessorHandler(s server.Server, hdlr DBAccessorHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&DBAccessor{hdlr}, opts...))
}

type DBAccessor struct {
	DBAccessorHandler
}

func (h *DBAccessor) User(ctx context.Context, in *UserRequest, out *UserResponse) error {
	return h.DBAccessorHandler.User(ctx, in, out)
}

func init() { proto.RegisterFile("dbaccessor.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 161 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x49, 0x4a, 0x4c,
	0x4e, 0x4e, 0x2d, 0x2e, 0xce, 0x2f, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x41, 0x88,
	0x14, 0x24, 0x29, 0x69, 0x72, 0x71, 0x87, 0x16, 0xa7, 0x16, 0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16,
	0x97, 0x08, 0x49, 0x71, 0x71, 0x94, 0x16, 0xa7, 0x16, 0xe5, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a,
	0x30, 0x6a, 0x70, 0x06, 0xc1, 0xf9, 0x4a, 0xf6, 0x5c, 0x3c, 0x10, 0xa5, 0xc5, 0x05, 0xf9, 0x79,
	0xc5, 0xa9, 0x42, 0x42, 0x5c, 0x2c, 0x48, 0xea, 0xc0, 0x6c, 0x21, 0x69, 0x2e, 0xce, 0xb4, 0xd2,
	0x9c, 0x9c, 0x78, 0xb0, 0x04, 0x13, 0xc4, 0x00, 0x90, 0x80, 0x5f, 0x62, 0x6e, 0xaa, 0x91, 0x2f,
	0x17, 0x97, 0x8b, 0x93, 0x23, 0xd4, 0x6e, 0x21, 0x7b, 0x2e, 0x16, 0x90, 0x71, 0x42, 0x92, 0x7a,
	0xc8, 0x0e, 0xd2, 0x43, 0x72, 0x8d, 0x94, 0x14, 0x36, 0x29, 0x88, 0xed, 0x4a, 0x0c, 0x49, 0x6c,
	0x60, 0xff, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc9, 0xe8, 0x87, 0xf1, 0xe3, 0x00, 0x00,
	0x00,
}
